package com.tangchao.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum ExceptionEnum {

    //特定状态码  501:用户已封禁,
    INVALID_USERNAME_PASSWORD(400, "无效用户名或密码"),
    INVALID_USER_NOT_FOND(404, "用户不存在！"),
    PASSWORD_NOT_ERROR(500, "密码不正确！"),
    INVALID_USER_BANNED(501,"您的账户已被冻结,请联系客服工作人员"),
    INVALID_VERIFY_CODE(400, "无效验证码"),
    USER_PHONE_NOTERROR(404, "手机号码错误！"),
    INVALID__PASSWORD_LENGTH(400, "密码长度6-16位"),
    USER_PHONE_NOT_ERROR(404, "手机号没注册！"),
    USER_PHONE_ALREADY_EXIST(400, "手机号已注册！"),
    INVALID_CART_DATA_TYPE(400, "参数不对！"),
    USER_NOT_AUTHORIZED(401, "用户未登录!"),
    USER_ACCOUNT_SETTINGS(500, "设置失败!"),
    GOODS_NOT_FOND(404, "商品不存在！"),
    CART_NOT_FOUND(404, "购物车为空!"),
    GOODS_DETAIL_NOT_FOND(404, "购买商品不能为空！"),
    CREATE_ORDER_ERROR(500, "创建订单失败！"),
    ADDRESS_SAVE_ERROR(500, "新增地址失败！"),
    ORDER_NOT_ERROR(404, "订单不存在"),
    ADDRESS_NOT_FOND(404, "收货地址不存在！"),
    UPDATE_CUSTOMER_ERROR(400, "积分获取失败！"),
    WITHDRAW_CUSTOMER_ERROR(400, "提现失败！"),
    STOCK_INSUFFICIENT_ERROR(402, "库存不足！"),
    UPPER_LIMIT_OF_PURCHASE(400, "包尾资源不足"),
    LIMIT_PURCHASE_LIMIT(400, "已达本团购买次数上限"),
    SHOPPING_CART_IS_FULL(400, "购物车数量已经存满啦~"),
    COLLECTION_NOT_ERROR(500, "商品收藏失败!"),
    COLLECTION_IS_EXIT(500, "商品已存在收藏列表!"),
    ORDER_PAYMENT(500, "订单已付款!"),
    ORDER_CANCEL(500, "订单已取消!"),
    ORDER_TIMEOUT(500, "订单已超时!"),
    USER_BALANCE_INSUFFICIENT(500, "您的抽奖次数不足!"),
    CUSTOMER_BALANCE_INSUFFICIENT(500, "余额满10元时才可以申请提现!"),
    GOODS_IS_LOTTERY(500, "商品已开奖!"),
    ORDER_PAYMENT_ERROR(500, "订单支付失败!"),
    GOODS_LOTTERY_ERROR(500, "商品正在开奖!"),
    SELL_IS_DOWN(404, "商品已下架"),
    INV_IS_ZERO(400, "商品库存为0"),
    STAGE_IS_END(400, "商品已到期"),
    INTEGRAL_NOT_ERROR(400, "积分赠送失败!"),
    INVALID_FILE_TYPE(400, "无效的文件类型！"),
    UPLOAD_FILE_ERROR(500, "文件上传失败！"),
    INVALID_NOPASSWORD(400,"密码错误"),
    INVALID_FAILEDPASSWORD(400,"密码错误"),
    USER_IS_EXIT(500,"用户已存在!"),
    USER_NOT_EXIT(500,"用户不存在，请先注册!"),
    SMS_SEND_ERROR(500,"短信发送失败！"),
    SMS_CODE_ERROR(500,"验证码错误！"),
    SMS_FREQUENTLY(500,"发送短信验证码频率过高!"),
    OPEN_LOTTERY_ERROR(500,"开奖失败!"),
    REGISTERED_NOT_ERROR(500,"注册失败！"),
    GOODS_IS_NOT(400, "请输入商品信息"),
    GOODS_DELECT_ERROR(500,"删除商品失败"),
    GOODS_ADD_ERROR(500,"添加商品失败"),
    GOODS_UPDATE_ERROR(500,"修改失败"),
    NOT_ADD_LAYER(400,"不能增加的层级"),
    GOODS_TYPE_ADD_ERROR(500,"添加商品分类失败"),
    GOODS_TYPE_IS_NOT_ERROR(400,"添加商品分类失败"),
    GOODS_TYPE_IS_NOT(400, "请输入商品分类信息"),
    HAS_SUB_TYPE(400,"有子类型，不可修改"),
    SORT_NOT_ERROR(500,"异常错误"),
    SORT_DELECT_NOT_ERROR(500,"分类删除错失败"),
    PAYMENT_CODE_NOT_EXIST(404,"收款码不存在！"),
    CUSTOMER_SERVICE_NOT_EXIST(404,"客服充值不存在，请联系管理员！"),
    OPERATING_FAIL(500,"操作失败！"),
    GOODS_NO_IS_UP(400,"产品还未上架"),
    USER_ACCOUNT_BANNED(403,"用户账号已封禁,请联系管理员!"),
    REVIEW_SAVE_ERROR(500,"审核失败！"),
    STATE_SELECT_NO_1(400_3,"审核通过,才能确认提现"),
    STATE_SELECT_3(400_4,"您已经确认过提现了"),
    STATE_SELECT(400_2,"审核失败,请选择状态是待审核的提现申请记录"),
    CONFIG_NOT_FOND(400_1,"配置信息不存在!"),
    SMSType_NOT_FOND(400_1,"短信类型不存在！"),
    TRANSFER_RECORD_NOT_FOND(404,"调用记录不存在！"),
    ROBOT_TASK_EXIST(402,"机器人任务已存在"),
    RECHARGE_SAVE_ERROR(500,"充值失败！"),
    SHARE_MAKE_MONEY_ERROR(500,"分享赚钱暂不可使用，请联系管理员！"),
    USER_SIGN_OUT(601,"退出登录！"),
    UNAUTHORIZED    (404,"无权访问"),
    GOODS_NOT_EXIST(404,"优惠券不存在"),
    ACCOUNT_IS_BOUND(500,"账号已绑定了"),
    COLLECTION_NOT_FOND(500,"收款信息不存在！"),
    PHONE_VIRTUAL_ACCOUNT(505,"该号码为虚拟号！");
    ;
    private int code;
    private String msg;
}
